export type ReportingDirection = "purchase" | "sales";
export type ReportingPartyType = "customer" | "supplier";

export type SupplierBalanceByBrandProductRow = {
  organization_id: string;
  supplier_id: string | null;
  party_id: string | null;
  supplier_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  currency: string;
  debit_amount: number;
  credit_amount: number;
  balance_amount: number;
  latest_due_date: string | null;
  line_count: number;
};

export type CustomerBalanceByBrandProductRow = {
  organization_id: string;
  customer_id: string | null;
  party_id: string | null;
  customer_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  currency: string;
  debit_amount: number;
  credit_amount: number;
  balance_amount: number;
  latest_due_date: string | null;
  line_count: number;
};

export type OpenPurchaseOrdersByBrandProductRow = {
  organization_id: string;
  supplier_id: string | null;
  party_id: string | null;
  supplier_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  sales_order_id: string;
  sales_order_no: string;
  purchase_order_id: string;
  purchase_order_no: string;
  currency: string;
  status: string;
  transaction_date: string;
  ordered_qty: number;
  received_qty: number;
  open_qty: number;
  unit_price: number;
  open_amount: number;
};

export type OpenSalesOrdersByBrandProductRow = {
  organization_id: string;
  customer_id: string | null;
  party_id: string | null;
  customer_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  sales_order_id: string;
  sales_order_no: string;
  currency: string;
  status: string;
  transaction_date: string;
  ordered_qty: number;
  invoiced_qty: number;
  open_qty: number;
  unit_price: number;
  open_amount: number;
};

export type PurchasePriceVarianceReportRow = {
  id: string;
  organization_id: string;
  direction: ReportingDirection;
  party_type: ReportingPartyType;
  party_id: string | null;
  supplier_id: string | null;
  customer_id: string | null;
  party_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  document_type: string;
  document_id: string;
  document_no: string;
  document_line_id: string;
  sales_order_id: string;
  sales_order_no: string;
  purchase_order_id: string;
  purchase_order_no: string;
  quantity: number;
  po_unit_price: number | null;
  bill_unit_price: number | null;
  last_buy_price: number | null;
  sell_unit_price: number | null;
  minimum_sell_price: number | null;
  cost_unit_price: number | null;
  variance_amount: number | null;
  variance_percent: number | null;
  margin_amount: number | null;
  margin_percent: number | null;
  severity: string;
  status: string;
  transaction_date: string;
  currency: string;
  created_at: string;
  updated_at: string;
};

export type BillLineRow = {
  id: string;
  organization_id: string;
  bill_id: string;
  line_index: number;
  purchase_order_id: string;
  purchase_order_no: string;
  supplier_id: string | null;
  supplier_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  old_code: string;
  description: string;
  oem_no: string;
  hs_code: string;
  qty: number;
  buy_price: number;
  line_total: number;
  weight_kg: number | null;
  currency: string;
  origin: string;
  notes: string;
  created_at: string;
  updated_at: string;
};

export type InvoiceLineRow = {
  id: string;
  organization_id: string;
  invoice_id: string;
  line_index: number;
  sales_order_id: string;
  sales_order_no: string;
  sales_order_ids: string[];
  customer_id: string | null;
  customer_name: string;
  warehouse_id: string | null;
  warehouse_code: string;
  warehouse_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  old_code: string;
  description: string;
  oem_no: string;
  hs_code: string;
  qty: number;
  buy_price: number;
  sell_price: number;
  purchase_total: number;
  sales_total: number;
  profit_total: number;
  margin_percent: number;
  weight_kg: number | null;
  currency: string;
  origin: string;
  notes: string;
  lifecycle_status: string | null;
  lifecycle_note: string | null;
  lifecycle_warning: string | null;
  created_at: string;
  updated_at: string;
};

export type AccountTransactionRow = {
  id: string;
  organization_id: string;
  party_type: ReportingPartyType;
  party_id: string | null;
  customer_id: string | null;
  supplier_id: string | null;
  party_name: string;
  direction: "receivable" | "payable";
  source_type: string;
  source_id: string;
  source_no: string;
  source_line_id: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  description: string;
  quantity: number;
  debit_amount: number;
  credit_amount: number;
  due_date: string | null;
  transaction_date: string;
  currency: string;
  warehouse_id: string | null;
  status: string;
  created_at: string;
  updated_at: string;
};

export type CommercialLineFactRow = {
  id: string;
  organization_id: string;
  direction: ReportingDirection;
  party_type: ReportingPartyType;
  party_id: string | null;
  supplier_id: string | null;
  customer_id: string | null;
  party_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  description: string;
  document_type: string;
  document_id: string;
  document_no: string;
  document_line_id: string;
  sales_order_id: string;
  sales_order_no: string;
  sales_order_ids: string[];
  purchase_order_id: string;
  purchase_order_no: string;
  quantity: number;
  unit_price: number;
  total_amount: number;
  currency: string;
  cost_amount: number;
  margin_amount: number;
  warehouse_id: string | null;
  transaction_date: string;
  due_date: string | null;
  status: string;
  created_at: string;
  updated_at: string;
};

export type PriceVarianceCheckRow = {
  id: string;
  organization_id: string;
  direction: ReportingDirection;
  party_type: ReportingPartyType;
  party_id: string | null;
  supplier_id: string | null;
  customer_id: string | null;
  party_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  document_type: string;
  document_id: string;
  document_no: string;
  document_line_id: string;
  sales_order_id: string;
  sales_order_no: string;
  purchase_order_id: string;
  purchase_order_no: string;
  quantity: number;
  po_unit_price: number | null;
  bill_unit_price: number | null;
  last_buy_price: number | null;
  sell_unit_price: number | null;
  minimum_sell_price: number | null;
  cost_unit_price: number | null;
  variance_amount: number | null;
  variance_percent: number | null;
  margin_amount: number | null;
  margin_percent: number | null;
  severity: string;
  status: string;
  transaction_date: string;
  currency: string;
  created_at: string;
  updated_at: string;
};

export type SalesMarginReportRow = {
  organization_id: string;
  customer_id: string | null;
  party_id: string | null;
  customer_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  normalized_code: string;
  currency: string;
  quantity: number;
  revenue_amount: number;
  cost_amount: number;
  margin_amount: number;
  margin_percent: number;
  line_count: number;
};

export type InventoryByBrandProductWarehouseRow = {
  organization_id: string;
  warehouse_id: string | null;
  warehouse_code: string;
  warehouse_name: string;
  brand_id: string | null;
  brand: string;
  product_id: string | null;
  product_code: string;
  description: string;
  origin: string;
  qty_in: number;
  qty_out: number;
  on_hand_qty: number;
  total_cost: number;
  last_moved_at: string | null;
};

export type ProcurementDashboardSummaryItem = {
  brand: string;
  product_code: string;
  normalized_code: string;
  cheapest_supplier: string;
  cheapest_price: number | null;
  second_supplier_name?: string | null;
  second_price?: number | null;
  price_gap?: number | null;
  price_gap_percent?: number | null;
  stock_qty?: number | null;
  lead_time_days?: number | null;
};

export type ProcurementDashboardSummary = {
  total_rollups: number;
  with_second_supplier: number;
  single_supplier_count: number;
  avg_gap_percent: number | null;
  high_gap_count: number;
  max_refreshed_at: string | null;
  top_high_gap_items: ProcurementDashboardSummaryItem[];
  single_supplier_items: ProcurementDashboardSummaryItem[];
};

export type RefreshReportingCoreResult = {
  status: "ok";
  organization_id: string;
  bill_lines: number;
  invoice_lines: number;
  account_transactions: number;
  commercial_line_facts: number;
  price_variance_checks: number;
};

export type ReportingCoreRefreshRunRow = {
  id: string;
  organization_id: string | null;
  started_at: string;
  finished_at: string | null;
  duration_ms: number | null;
  status: "running" | "succeeded" | "failed" | string;
  error_message: string | null;
  bill_lines_count: number | null;
  invoice_lines_count: number | null;
  account_transactions_count: number | null;
  commercial_line_facts_count: number | null;
  price_variance_checks_count: number | null;
  supplier_price_rollups_count?: number | null;
};

export type RefreshReportingCoreLoggedResult = {
  run_id: string;
  organization_id: string;
  started_at: string;
  finished_at: string;
  duration_ms: number;
  status: "succeeded" | "failed" | string;
  error_message?: string | null;
  bill_lines_count?: number;
  invoice_lines_count?: number;
  account_transactions_count?: number;
  commercial_line_facts_count?: number;
  price_variance_checks_count?: number;
  supplier_price_rollups_count?: number;
  refresh_result?: RefreshReportingCoreResult;
};
